# Generated by Django 5.2.2 on 2025-06-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_visitor_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="referenced_documents",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
